Repository yashksaini-coder/Leetcode-Journal, pull requests merged in 2025-02, with the labels that each got.

#119 Refractor code for the application
  app/learn-more/components/TabContainer.tsx
  app/learn-more/page.tsx
  app/resources/page.tsx
  components/BlogListItem.tsx
  components/SocialLinks.tsx
  components/Stats.tsx
  components/dashboardComponents/DashboardContentSkeleton.tsx
  components/dashboardComponents/DashboardNavbar.tsx
  components/footer.tsx
  components/navbar.tsx
  components/ui/timeline.tsx
  package-lock.json
Labels: enhancement, Under Review

#117 fix: added proper state management and route verification of dashboard
  app/auth/register/page.tsx
  components/AuthComponent/SearchParamsWrapper.tsx
  components/AuthComponent/SignupForm.tsx
  components/DashboardV2/V2Navbar.tsx
  hooks/useAuth.ts
  store/AuthStore/useAuthStore.ts
Labels: bug, SWOC, Under Review, Backend, High Priority

#122 Dashboard V2 update
  GQL_Queries/contest.ts
  GQL_Queries/index.ts
  GQL_Queries/languageStats.ts
  GQL_Queries/recentSubmit.ts
  app/api/leetcode/route.ts
  app/api/leetcode/stats.ts
  app/api/leetcode/userDetails/route.ts
  app/dashboard/page.tsx
  app/styles/style.css
  components/AuthComponent/Logout.tsx
  components/ui/sonner.tsx
  lib/leetcode-calendar-theme.ts
  package-lock.json
  package.json
  store/LeetcodeStore/useLeetcodeStore.ts
  utils/leetcode/leetcodeContollers.ts
Labels: Under Review
