Repository yashksaini-coder/Leetcode-Journal, pull requests merged in 2025-01, with the labels that each got.

#8 feat/added workflows
  .github/workflows/autoComment.yaml
  .github/workflows/newContibuter.yaml
Labels: SWOC, Beginner

#15 Created ISSUE TEMPLATE folder with BUG-REPORT, DOC-UPDATE, FEATURE REQUEST - GENERAL ISSUE.yaml files
  .github/ISSUE_TEMPLATE/Bug-report.yaml
  .github/ISSUE_TEMPLATE/Feature-Request.yaml
  .github/ISSUE_TEMPLATE/General_issue.yaml
  .github/Pull_request_Template.md
Labels: good first issue, SWOC, Beginner

#16 feat: 🎸 Add Navbar component and integrate the theme toggle button
  app/page.tsx
  components/header.tsx
  components/ui/sheet.tsx
  package-lock.json
  package.json
Labels: SWOC, Beginner

#32 added Faq page. resolved issue #29 https://github.com/yashksaini-coder/Leetcode-Journal/issues/29
  app/FAQ/component/contact-section.tsx
  app/FAQ/component/faq-component.tsx
  app/FAQ/component/layout.tsx
  app/FAQ/page.tsx
  app/page.tsx
  components/SocialLinks.tsx
  components/navbar.tsx
  components/ui/input.tsx
  package-lock.json
  package.json
Labels: enhancement, SWOC, Intermediate, Under Review, Changes requested

#37 feature/fix-auth
  app/api/auth/register/route.ts
  app/api/auth/user/route.ts
  app/auth/register/page.tsx
  app/auth/signin/page.tsx
  app/auth/verify/page.tsx
  app/dashboard/page.tsx
  components/AuthComponent/AuthBottom.tsx
  components/AuthComponent/SigninForm.tsx
  components/AuthComponent/SignupForm.tsx
  components/Buttons/LandingEmerlandButton.tsx
  components/Buttons/LoadingButton.tsx
  components/LandingComponents/PriceCard.tsx
  components/LoginForm.tsx
  components/SignupForm.tsx
  components/header.tsx
  components/navbar.tsx
  components/ui/alert.tsx
  components/ui/skeleton.tsx
  lib/database/prismaClient.ts
  package-lock.json
  package.json
  prisma/migrations/20250108154722_init/migration.sql
  prisma/migrations/20250108161333_usernamefix/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  store/AuthStore/useAuthStore.ts
  types/typeInterfaces.ts
  utils/hashing.ts
  validations/validation.ts
Labels: enhancement, SWOC, Advanced

#36 Improved Theme Toggle Button Functionality
  components/theme-toggle.tsx
Labels: good first issue, SWOC, Beginner

#38 added learn more page
  app/learn-more/components/TabContainer.tsx
  app/learn-more/page.tsx
  package-lock.json
Labels: good first issue, SWOC, Beginner, Under Review, Changes requested

#65 fix: autocomment on pr workflow issue
  .github/workflows/autoComment.yaml
Labels: SWOC, Beginner

#72 ⭐ Feat-adding favicon
  app/favicon.ico
  app/leetcodeJournal.ico
Labels: enhancement, good first issue, SWOC, Beginner, Frontend

#78 Enhance sign
  components/AuthComponent/SigninForm.tsx
  components/AuthComponent/SignupForm.tsx
  components/header.tsx
  public/dark-auth.jpg
  public/light-auth.jpg
  tailwind.config.ts
Labels: enhancement, SWOC, Intermediate, Frontend

#82 middleware fix
  app/actions/action.ts
  app/api/auth/register/route.ts
  app/api/auth/user/route.ts
  components/AuthComponent/SigninForm.tsx
  components/header.tsx
  middleware.ts
  package-lock.json
  package.json
  store/AuthStore/useAuthStore.ts
  utils/supabase/client.ts
  utils/supabase/middleware.ts
  utils/supabase/server.ts
Labels: enhancement, SWOC, Intermediate, Backend

#88 FAQ + learn-more made responsive v2
  app/FAQ/page.tsx
  app/learn-more/page.tsx
Labels: enhancement, SWOC, Intermediate, Frontend

#90 Feature/Sidebar
  app/dashboard/layout.tsx
  app/dashboard/page.tsx
  app/dashboard/profile/page.tsx
  components/dashboardComponents/AppSidebar.tsx
  store/AuthStore/useAuthStore.ts
Labels: bug, enhancement, SWOC, Beginner, Frontend, Medium Priority

#93 Feature/Resposive-Sidebar
  app/dashboard/layout.tsx
  components/dashboardComponents/AppSidebar.tsx
  components/dashboardComponents/MobileSidebar.tsx
  data/SidebarData.ts
Labels: SWOC, Intermediate, Frontend, Medium Priority

#96 Bug/middleware
  app/dashboard/profile/page.tsx
  components/dashboardComponents/AppSidebar.tsx
  package-lock.json
  package.json
  utils/supabase/middleware.ts
Labels: enhancement, SWOC, Advanced, Backend, High Priority

#101 revamp footer section
  components/SocialLinks.tsx
  components/footer.tsx
Labels: enhancement, SWOC, Intermediate, Frontend, Medium Priority

#99 Hero Component Refactored v2
  .gitignore
  app/globals.css
  app/page.tsx
  app/starStyles.css
  app/title.css
  components/navbar.tsx
  components/theme-toggle.tsx
  components/ui/highlight.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: enhancement, SWOC, Frontend, Low Priority

#100 Feature/Blogs
  app/blogs/[year]/[slug]/page.tsx
  app/blogs/page.tsx
  components/BlogListItem.tsx
  components/ui/scroll-area.tsx
  components/ui/timeline.tsx
  content/blog/2023/Blog1.md
  content/blog/2023/Blog2.md
  content/blog/2024/Blog1.md
  content/blog/2024/Blog2.md
  content/blog/2025/Cow.md
  content/blog/2025/NextJS.md
  data/SidebarData.ts
  lib/getBlogs.ts
  package-lock.json
  package.json
Labels: enhancement, SWOC, Frontend

#107 feat: ✨ Implement AlertDialog for logout confirmation and remove Auro…
  components/dashboardComponents/AppSidebar.tsx
  components/ui/alert-dialog.tsx
  components/ui/aurora-background.tsx
  package-lock.json
  package.json
Labels: enhancement, Under Review, Frontend

#108 navbar modification
  components/navbar.tsx
  components/ui/background-gradient.tsx
  components/ui/navbar-menu.tsx
Labels: enhancement, SWOC, Intermediate, Frontend, Medium Priority

#111 resources page ui
  app/resources/component/resource-card.tsx
  app/resources/component/ripple.tsx
  app/resources/component/support-section.tsx
  app/resources/page.tsx
  components/navbar.tsx
  tailwind.config.ts
Labels: enhancement, good first issue, SWOC, Frontend, High Priority
